#!/bin/zsh
# Oscar's Saying Tool
# Written by: https://m.me/Rammy
# Description: This tool receives input and has say speak it.

# Functions:

	utter() { print "$1"; say "$1"; }

	intro() { utter "Whatever you type, I will say for you."; }

# Program:

	intro

	while do
		read words
		say "$words"
	done
	
