#!/bin/zsh
# Oscar's Saying Tool
# Written by: https://m.me/Rammy
# Description: This tool receives input and has say speak it.

# Functions:

	utter() { printf $1; say -v Fred $1; }

	intro() { utter "Whatever you type, I will say for you."; }

	more() { utter "I am the script file $0"; }

# Program:

	utter "Oscar's Saying Tool" && echo && sleep 3

	request="Type your name: "; utter $request &
	read name
	say -v Samantha "Welcome $name!"; sleep 2

	intro; sleep 1; echo

	while do
		read words
		say "$words"
	done
	
