#!/bin/zsh
# Oscar's Saying Tool
# Written by: https://m.me/Rammy
# Description: This tool receives input and has say speak it.

# Functions:

        utter() { print $1; say -v Samantha $1; }

        instruct() { utter "Type: control-L return to clear screen.\n
                        Control-C to exit the program."; }

# Program:

        instruct
        while do
                read words
                if [[ $words = ^L ]]
                then
                        clear
                elif [[ $words = \\* ]]
                then
                        ~/Downloads/ost-main/psm
                else
                        say "$words"
                fi
        done
        
